# Site settings
title: Rodolfo Maciel
email: rodolfomaciel@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Como gerar uma idéia de negócio, validar sua proposta e criar um negócio digital de sucesso. Como criar e expandir um negócio online do zero usando marketing digital.
author: Rodolfo Maciel
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rodolfomaciel.com/" # the base hostname & protocol for your site


permalink:   /:title/
paginate: 5


disqus-shortname: rodolfomaciel83
twitter_username: _rodolfomaciel
facebook_username:  rodolfomaciel
linkedin__username:  rodolfomaciel
google_username:  +RodolfoMaciel83

# Build settings
markdown: kramdown
