# Site settings
title: "Marketing Digital - O Guia Online Gratuito"
email: rodolfomaciel@outlook.com
description: "Como criar um Negócio Online "
author: Rodolfo Maciel
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rodolfomaciel.com/" # the base hostname & protocol for your site


permalink:   /:title/
paginate: 9000


disqus-shortname: disqus_vlPoledEJc
twitter_username: _rodolfomaciel
facebook_username:  rodolfomaciel
linkedin__username:  rodolfomaciel
google_username:  +RodolfoMaciel83
facebookid: 1621242431464641

# Build settings
markdown: kramdown
